### ISSUE TITLE
Start "Discussions" on opendp/opendp

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp-documentation#27]
Notes regarding creating a GitHub Discussions Forum on the opendp/opendp repository.
- Not ideal in that it's at the repository rather than org level. 
- The preference is to only have a single forum for the opendp org
   - This would replace Gitter for now. ([Gitter is moving/being merged into Matrix](https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix), e.g. we may look at that in the near future)
- Given team resources, it's more manageable to keep everything within GitHub

---

**Tasks:** 
- [x] Add GitHub Discussion + initial topics
  - [x] OpenDP Library
  - [x] Differential Privacy (Theory/Practice)
  - [x] SmartNoise ~~Library, SQL, synthesizers~~
  - [x] Getting Involved
- [x] Update repository README page to link to the discussion. (Also remove Gitter links when appropriate)
  - [x] docs.opendp.org - pull request #39
  - [x] smartnoise-sdk
  - [x] smartnoise-core
  - [x] smartnoise-core-python
  - [x] smartnoise-samples
  - [x] opendp
  - [x] dpcreator
- [x] Gitter
  - [x] Link to the new discussions forum
